apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vault
  namespace: vault
  annotations:
    cert-manager.io/cluster-issuer: __CLUSTER_ISSUER__
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/service.serversscheme: "https"
    traefik.ingress.kubernetes.io/service.serverstransport: vault-transport
spec:
  ingressClassName: public
  tls:
  - hosts:
    - __VAULT_HOST__
    secretName: vault-tls
  rules:
  - host: __VAULT_HOST__
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vault
            port:
              number: 8200
