{{- if and .Values.oauth2proxy.enabled .Values.oauth2proxy.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "oauth2-proxy.serviceAccountName" . }}
  labels:
    {{- include "oauth2-proxy.labels" . | nindent 4 }}
{{- end }}
