# DEV-specific image-builder config. Phase A: image-builder runs on DEV only.
externalsecret-git-ssh:
  externalSecret:
    vaultPath: dev/app/image-builder

externalsecret-webhooks:
  externalSecret:
    vaultPath: dev/app/image-builder
