{{- if .Values.acrSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.acrSecret.name }}
  namespace: {{ .Values.acrSecret.namespace | default .Release.Namespace }}
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: {{ .Values.acrSecret.secretStoreName }}
    kind: {{ .Values.acrSecret.secretStoreKind }}
  target:
    name: {{ .Values.acrSecret.targetSecretName }}
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ "{{ .dockerconfigjson }}" }}"
  data:
    - secretKey: dockerconfigjson
      remoteRef:
        key: {{ .Values.acrSecret.vaultPath }}
        property: {{ .Values.acrSecret.property }}
{{- end }}
