{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name }}
  namespace: {{ .Values.externalSecret.namespace | default .Release.Namespace }}
spec:
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreName | default .Values.global.secretStoreName }}
    kind: {{ .Values.externalSecret.secretStoreKind | default "SecretStore" }}
  target:
    name: {{ .Values.externalSecret.targetSecretName }}
    creationPolicy: Owner
  data:
  {{- range .Values.externalSecret.data }}
  - secretKey: {{ .secretKey }}
    remoteRef:
      nullBytePolicy: Ignore
      key: {{ $.Values.externalSecret.vaultPath }}
      property: {{ .property }}
  {{- end }}
{{- end }}
