image:
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent

replicas: 1

containerPort: 8080

command: []
args: []

env: []
envSources: []

serviceAccountName: ""

volumeMounts: []
volumes: []

podSecurityContext: {}
containerSecurityContext: {}

livenessProbe: {}
readinessProbe: {}

resources: {}

imagePullSecrets: []
hostAliases: []

terminationGracePeriodSeconds: 30

service:
  enabled: true
  type: ClusterIP
  port: 8080
