# Per-namespace SecretStore (visible as an ArgoCD-managed resource).
secret-store: {}

# Vault path for PROD.
externalSecret:
  vaultPath: prod/app/postgresql

postgres-data:
  pvc:
    storageSize: "50Gi"

postgres:
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: "2"
      memory: 4Gi

prometheus-postgres-exporter:
  config:
    datasource:
      host: postgresql-prod.postgresql.svc.cluster.local
