{{- if .Values.exporterSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.exporterSecret.name }}
  namespace: {{ .Values.exporterSecret.namespace | default .Release.Namespace }}
spec:
  secretStoreRef:
    name: {{ .Values.exporterSecret.secretStoreName | default .Values.global.secretStoreName }}
    kind: {{ .Values.exporterSecret.secretStoreKind | default "SecretStore" }}
  target:
    name: {{ .Values.exporterSecret.targetSecretName }}
    creationPolicy: Owner
    {{- with .Values.exporterSecret.template }}
    template:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  data:
  {{- range .Values.exporterSecret.data }}
  - secretKey: {{ .secretKey }}
    remoteRef:
      key: {{ $.Values.exporterSecret.vaultPath }}
      property: {{ .property }}
  {{- end }}
{{- end }}
