version: 1
metadata:
  name: Seq Forward Auth
  labels:
    blueprints.goauthentik.io/instantiate: "true"
entries:
  - identifier: seq-proxy-provider
    model: authentik_providers_proxy.proxyprovider
    attrs:
      name: Seq
      authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
      external_host: https://log.${IDP_ENV}.${IDP_DOMAIN}
      mode: forward_domain
      cookie_domain: .${IDP_ENV}.${IDP_DOMAIN}
      access_token_validity: hours=24
      property_mappings:
        - !Find [authentik_providers_oauth2.scopemapping, [scope_name, openid]]
        - !Find [authentik_providers_oauth2.scopemapping, [scope_name, profile]]
        - !Find [authentik_providers_oauth2.scopemapping, [scope_name, email]]
  - identifier: seq-app
    model: authentik_core.application
    attrs:
      name: Seq
      slug: seq
      provider: !KeyOf seq-proxy-provider
      meta_launch_url: https://log.${IDP_ENV}.${IDP_DOMAIN}/
      open_in_new_tab: true
      group: Observability
