# TEST-specific objectstore config — only the Vault paths differ per env.
externalsecret-garage:
  externalSecret:
    vaultPath: test/app/objectstore

externalsecret-filestash:
  externalSecret:
    vaultPath: test/app/objectstore
